config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :praises
  resources :prayers
  devise_for :users

  root 'static#home'

  get 'user' => 'static#user'
  get 'team' => 'static#team'
  get 'answered' => 'static#answered'
  get 'about' => 'static#about'

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/praise.rb
class Praise < ActiveRecord::Base
  belongs_to :user
end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prayers, dependent: :destroy
  has_many :praises, dependent: :destroy
  has_one :profile

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/praises_controller.rb
class PraisesController < ApplicationController
  before_action :set_praise, only: [:show, :edit, :update, :destroy]

  # GET /praises
  # GET /praises.json
  def index
    @user = current_user
    @praises = @user.praises.reverse
  end

  # GET /praises/1
  # GET /praises/1.json
  def show
  end

  # GET /praises/new
  def new
    @praise = Praise.new
    @praise.user_id = current_user.id
    @praise.save
  end

  # GET /praises/1/edit
  def edit
  end

  # POST /praises
  # POST /praises.json
  def create
    @praise = Praise.new(praise_params)

    respond_to do |format|
      if @praise.save
        format.html { redirect_to @praise, notice: 'Praise was successfully created.' }
        format.json { render :show, status: :created, location: @praise }
      else
        format.html { render :new }
        format.json { render json: @praise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /praises/1
  # PATCH/PUT /praises/1.json
  def update
    respond_to do |format|
      if @praise.update(praise_params)
        format.html { redirect_to @praise, notice: 'Praise was successfully updated.' }
        format.json { render :show, status: :ok, location: @praise }
      else
        format.html { render :edit }
        format.json { render json: @praise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /praises/1
  # DELETE /praises/1.json
  def destroy
    @praise.destroy
    respond_to do |format|
      format.html { redirect_to praises_url, notice: 'Praise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_praise
      @praise = Praise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def praise_params
      params.require(:praise).permit(:title, :description)
    end
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: [:show, :edit, :update, :destroy]

  # GET /prayers
  # GET /prayers.json
  def index
    @user = current_user
    @prayers = @user.prayers.where(:answered => FALSE).reverse
  end

  # GET /prayers/1
  # GET /prayers/1.json
  def show
  end

  # GET /prayers/new
  def new
    @prayer = Prayer.new
    @prayer.user_id = current_user.id
    @prayer.save
  end

  # GET /prayers/1/edit
  def edit
  end

  # POST /prayers
  # POST /prayers.json
  def create
    @prayer = Prayer.new(prayer_params)

    respond_to do |format|
      if @prayer.save
        format.html { redirect_to @prayer, notice: 'Prayer was successfully created.' }
        format.json { render :show, status: :created, location: @prayer }
      else
        format.html { render :new }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prayers/1
  # PATCH/PUT /prayers/1.json
  def update
    respond_to do |format|
      if @prayer.update(prayer_params)
        format.html { redirect_to @prayer, notice: 'Prayer was successfully updated.' }
        format.json { render :show, status: :ok, location: @prayer }
      else
        format.html { render :edit }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayers/1
  # DELETE /prayers/1.json
  def destroy
    @prayer.destroy
    respond_to do |format|
      format.html { redirect_to prayers_url, notice: 'Prayer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer
      @prayer = Prayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prayer_params
      params.require(:prayer).permit(:title, :description, :answered, :email)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profile = Profile.where(user_id: current_user.id).take
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.user_id = current_user.id
    @profile.save
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :about_me, :profile_img)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def user
    @profile = Profile.where(user_id: current_user.id).take
    @prayers = Prayer.where(user_id: current_user.id)
    @praises = Praise.where(user_id: current_user.id)
    @answered = Prayer.where(user_id: current_user.id).where(answered: TRUE)
  end

  def about
  end

  def answered
    @user = current_user
    @prayers = @user.prayers
    @answered = @prayers.where(:answered => TRUE).reverse
  end

  def team
    @user = current_user
    @warriors = @user.all_following
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/praises_helper.rb
module PraisesHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPrayerTeam.org</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/nav" %>
  <div class="container">
    <%= yield %>
  </div> <!-- End Main Container -->
</body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= nav_link_to 'MyPrayerTeam.org', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-nav">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <%= nav_link_to "Home", user_path, {}, {:wrapper => 'li'} %>
        <% end %>
        <% unless user_signed_in? %>
          <%= nav_link_to "Home", root_path, {}, {:wrapper => 'li'} %>
          <%= nav_link_to 'About', about_path, {}, {:wrapper => 'li'} %>
        <% end %>
        <% if user_signed_in? %>
          <%= nav_link_to "My Profile", profiles_path, {}, {:wrapper => 'li'} %>
          <%= nav_link_to "My Team", team_path, {}, {:wrapper => 'li'} %>
          <%= nav_link_to "Answered", answered_path, {}, {:wrapper => 'li'} %>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <%= nav_link_to "My Account", edit_user_registration_path, {}, {:wrapper => 'li'} %>
        <%= nav_link_to "Log out", destroy_user_session_path, {method: :delete}, {:wrapper => 'li'} %>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/praises/_form.html.erb
<%= bootstrap_form_for(@praise) do |f| %>
  <% if @praise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@praise.errors.count, "error") %> prohibited this praise from being saved:</h2>

      <ul>
      <% @praise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :title %>
    <%= f.text_area :description %>
    <%= f.submit %>
<% end %>

app/views/praises/edit.html.erb
<h1>Editing Praise</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @praise %> |
<%= link_to 'Back', praises_path %>

app/views/praises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  My Praises
  <%= link_to new_praise_path, class: "btn btn-success" do %>
    <%= fa_icon "plus" %>
  <% end %>
</h1>

    <% @praises.each do |praise| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= praise.title %>
          <span class="pull-right"><%= fa_icon "calendar" %> <%= praise.created_at.strftime("%A, %b %d, %Y at %H:%M") %></span>
        </div>
        <div class="panel-body">
          <%= praise.description %>
        </div>
        <div class="panel-footer">
          <%= link_to edit_praise_path(praise), class: "btn btn-info" do %>
            <%= fa_icon "pencil" %>
          <% end %>
          <%= link_to praise, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
            <%= fa_icon "trash" %>
          <% end %>
          <%= link_to praise_path(praise), class: "btn btn-default pull-right" do %>
            <%= fa_icon "comment" %> Comments
          <% end %>
        </div>
      </div>
    <% end %>

<br>

app/views/praises/new.html.erb
<h1>New Praise</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', praises_path %>

app/views/praises/show.html.erb
<%= link_to 'Back', praises_path %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @praise.title %>
    <span class="pull-right"><%= fa_icon "calendar" %> <%= @praise.created_at.strftime("%A, %b %d, %Y at %H:%M") %></span>
  </div>
  <div class="panel-body">
    <%= @praise.description %>
  </div>
  <div class="panel-footer">
    <% if @praise.user == current_user %>
      <%= link_to edit_praise_path(@praise), class: "btn btn-info" do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to @praise, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
  </div>
</div>
<ul class="media-list">
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/7" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Kelly R.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Just prayed for you! Hang in there!

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/3" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">James B.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      A lectus alias varius itaque, porttitor odio curae eleifend hic nunc assumenda? Quae leo cursus totam! Exercitation, eius convallis nascetur.

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/1" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Jess J.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Habitasse occaecati dignissim, eaque sint consequatur? Aperiam sapien! Labore massa harum exercitationem, odio cubilia ligula! Ad, sed habitasse scelerisque facilisi.
    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/7" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Kelly R.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Just prayed for you! Hang in there!

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/3" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">James B.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      A lectus alias varius itaque, porttitor odio curae eleifend hic nunc assumenda? Quae leo cursus totam! Exercitation, eius convallis nascetur.

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/1" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Jess J.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Habitasse occaecati dignissim, eaque sint consequatur? Aperiam sapien! Labore massa harum exercitationem, odio cubilia ligula! Ad, sed habitasse scelerisque facilisi.

    </div>
  </li>
</ul>

app/views/prayers/_form.html.erb
<%= bootstrap_form_for(@prayer) do |f| %>
  <% if @prayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prayer.errors.count, "error") %> prohibited this prayer from being saved:</h2>

      <ul>
      <% @prayer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <%= f.check_box :answered %>
  <%= f.submit %>
<% end %>

app/views/prayers/edit.html.erb
<h1>Editing Prayer</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', prayers_path %>

app/views/prayers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  My Prayers
  <%= link_to new_prayer_path, class: "btn btn-success" do %>
    <%= fa_icon "plus" %>
  <% end %>
</h1>

    <% @prayers.each do |prayer| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= prayer.title %>
          <span class="pull-right"><%= fa_icon "calendar" %> <%= prayer.created_at.strftime("%A, %b %d, %Y") %></span>
        </div>
        <div class="panel-body">
          <%= prayer.description %>
        </div>
        <div class="panel-footer">
          <%= link_to edit_prayer_path(prayer), class: "btn btn-info" do %>
            <%= fa_icon "pencil" %>
          <% end %>
          <%= link_to prayer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
            <%= fa_icon "trash" %>
          <% end %>
          <a href="#" class="btn btn-default pull-right"><i class="fa fa-comment"></i> Comments</a>
        </div>
      </div>
      <% unless prayer === @prayers.last %>
      <ul>
        <li></li>
        <li></li>
        <li></li>
      </ul>
      <% end %>
    <% end %>

<br>

app/views/prayers/new.html.erb
<h1>New Prayer</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', prayers_path %>

app/views/prayers/show.html.erb
<%= link_to 'Back', prayers_path %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @prayer.title %>
    <span class="pull-right"><%= fa_icon "calendar" %> <%= @prayer.created_at.strftime("%A, %b %d, %Y at %H:%M") %></span>
  </div>
  <div class="panel-body">
    <%= @prayer.description %>
  </div>
  <div class="panel-footer">
    <% if @prayer.user == current_user %>
      <%= link_to edit_prayer_path(@prayer), class: "btn btn-info" do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to @prayer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
  </div>
</div>
<ul class="media-list">
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/7" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Kelly R.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Just prayed for you! Hang in there!

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/3" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">James B.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      A lectus alias varius itaque, porttitor odio curae eleifend hic nunc assumenda? Quae leo cursus totam! Exercitation, eius convallis nascetur.

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/1" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Jess J.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Habitasse occaecati dignissim, eaque sint consequatur? Aperiam sapien! Labore massa harum exercitationem, odio cubilia ligula! Ad, sed habitasse scelerisque facilisi.
    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/7" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Kelly R.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Just prayed for you! Hang in there!

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/3" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">James B.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      A lectus alias varius itaque, porttitor odio curae eleifend hic nunc assumenda? Quae leo cursus totam! Exercitation, eius convallis nascetur.

    </div>
  </li>
  <hr>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object img-circle" src="http://lorempixel.com/64/64/people/1" alt="profile-img">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Jess J.<br><small>11:45a, Tuesday, February 05, 2016</small></h4>
      Habitasse occaecati dignissim, eaque sint consequatur? Aperiam sapien! Labore massa harum exercitationem, odio cubilia ligula! Ad, sed habitasse scelerisque facilisi.

    </div>
  </li>
</ul>

app/views/profiles/_form.html.erb
<%= bootstrap_form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_area :about_me, id: "profile-editor", class: "wysihtml5", placeholder: "Share a bit about yourself..." %>
    <%= f.text_field :profile_img %>
    <%= f.submit %>
<% end %>
<script type="text/javascript">
  $(document).on('page:load', function(){
    window['rangy'].initialized = false
  })

  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({ toolbar:{ "fa": true, "image": false, "font-styles": false } });
    });

  })
</script>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
    <br>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', profiles_path %>
  </div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="panel panel-default">
  <% unless @profile == nil %>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4 text-center">
          <h3><%= @profile.first_name %> <%= @profile.last_name %></h3>
          <img id="profile-img" src="<%= @profile.profile_img %>" alt="" class="img-circle">
          <p><br>Member since: <%= current_user.created_at.strftime("%B %Y") %></p>
        </div>
        <div class="col-md-8">
          <h3>About Me</h3>
          <%= @profile.about_me.html_safe %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <% if @profile.nil? %>
        <%= link_to new_profile_path do %>
        <%= fa_icon "plus" %> New Profile
        <%end %>
      <% end %>
      <%= link_to edit_profile_path(@profile), class: "btn btn-info" do %>
        <%= fa_icon "pencil" %>
      <% end %>
    </div>
  <% else %>
    <div class="panel-body text-center">
      <h2>Okay, first things first.</h2>
      <%= link_to new_profile_path(@profile), class: "btn btn-info" do %>
        <%= fa_icon "plus" %> Create Profile
      <% end %>
    </div>
  <% end %>
  </div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="panel panel-default">
  <% unless @profile == nil %>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4 text-center">
          <h3><%= @profile.first_name %> <%= @profile.last_name %></h3>
          <img id="profile-img" src="<%= @profile.profile_img %>" alt="" class="img-circle">
          <p><br>Member since: <%= current_user.created_at.strftime("%B %Y") %></p>
        </div>
        <div class="col-md-8">
          <h3>About Me</h3>
          <%= @profile.about_me.html_safe %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <% if @profile.nil? %>
        <%= link_to new_profile_path do %>
        <%= fa_icon "plus" %> New Profile
        <%end %>
      <% end %>
      <% if @profile.user_id == current_user.id %>
        <%= link_to edit_profile_path(@profile), class: "btn btn-info" do %>
          <%= fa_icon "pencil" %>
        <% end %>
      <% else %>
        <%= link_to "Back", team_path %>
      <% end %>
    </div>
  <% else %>
    <div class="panel-body text-center">
      <h2>Okay, first things first.</h2>
      <%= link_to new_profile_path(@profile), class: "btn btn-info" do %>
        <%= fa_icon "plus" %> Create Profile
      <% end %>
    </div>
  <% end %>
  </div>